# Generated by Django 4.2.7 on 2024-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedfile',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='translatedfile',
            name='original_file',
            field=models.FileField(upload_to='original_files/'),
        ),
        migrations.AlterField(
            model_name='translatedfile',
            name='translated_file',
            field=models.FileField(blank=True, null=True, upload_to='translated_files/'),
        ),
    ]
