# Generated by Django 4.2.7 on 2024-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_remove_translatedfile_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TranslatedFile',
        ),
    ]
