# Generated by Django 4.2.7 on 2024-01-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_translatedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedfile',
            name='translated_file',
        ),
    ]
