# Generated by Django 4.2.7 on 2024-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPP', '0002_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='text',
            field=models.TextField(default='hello this is new text'),
        ),
    ]
