# Generated by Django 4.2.7 on 2024-01-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testPP', '0003_filemodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='text',
        ),
    ]
