# Generated by Django 4.2.7 on 2024-01-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testPP', '0004_remove_filemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
